### ISSUE TITLE
Document and enforce stack size limits

### ISSUE THREAD

**Issue by rmn30** [microsoft/cheriot-rtos#58]
Stacks larger than about 8 KiB are problematic for compartment switches because the switcher cannot guarantee that the remainder stack has a representable length.
In particular this [`csetboundsexact`](https://github.com/microsoft/cheriot-rtos/blob/e24f37fafa05d8eb23f81c76ee3b997c6b9415b3/sdk/core/switcher/entry.S#L184) might trap.
Given that stack bounds must be 16-byte aligned and the capability precision is 9 bits stacks up to `16 * 511 = 8176` bytes should be fine.

We should document this limit and possibly enforce it in the xmake and / or linker.

**Comment by davidchisnall** [comment]
Some of this code wants refactoring anyway.  I don't really like the fact that we're passing the thread init structures into the loader at compile time, because it means that we can't have a single loader binary and that makes auditing hard.  I'd like to move the initial thread state into declarative data so that it's checkable from the linker's report.

**Comment by davidchisnall** [comment]
This refactoring has been done, so this should now be easy.
